const members=[
 {name:'Adeeb',initials:'A',avatar:'a1',tags:['🎳 Activities','🍜 Asian','⚡ Adventure'],budget:120},
 {name:'Ahmed',initials:'A',avatar:'a2',tags:['🎮 Gaming','🍔 Burgers','🏠 Indoor'],budget:70},
 {name:'Kaveri',initials:'K',avatar:'a3',tags:['☕ Cafés','🍜 Asian','🥬 Vegetarian','😌 Chill'],budget:100},
 {name:'Saif',initials:'S',avatar:'a4',tags:['🎮 Gaming','🏆 Competitive','🎉 Social'],budget:100}
];
const venues={arcade:{id:'venue_01',name:'Pixel Arcade',icon:'🎮',price:35,tags:['gaming','competitive','social']},bowling:{id:'venue_02',name:'Neon Lanes Bowling',icon:'🎳',price:42,tags:['bowling','competitive','social']},korean:{id:'venue_03',name:'Seoul Table',icon:'🍜',price:30,tags:['asian','vegetarian','social']},burger:{id:'venue_04',name:'Stacked Burgers',icon:'🍔',price:24,tags:['burgers','casual','social']},dessert:{id:'venue_05',name:'Cloud 9 Mochi',icon:'🍦',price:12,tags:['dessert','asian','social']},cafe:{id:'venue_06',name:'Common Grounds',icon:'☕',price:22,tags:['cafe','chill','social']},creative:{id:'venue_07',name:'Clay Club Studio',icon:'🎨',price:28,tags:['creative','chill','social']},outdoor:{id:'venue_08',name:'Creekside Kayak',icon:'🛶',price:50,tags:['outdoor','adventure','competitive']}};
const plans=[
 {id:'competitive',icon:'🎳',title:'Competitive Night',places:[venues.bowling,venues.korean,venues.dessert],price:84,match:94,reason:'Great activity match for Adeeb and Saif while keeping Asian food for Kaveri.'},
 {id:'arcade',icon:'🎮',title:'Arcade Night',places:[venues.arcade,venues.burger,venues.dessert],price:69,match:91,reason:'A low-friction gaming run with a crowd-pleasing finish.'},
 {id:'chill',icon:'☕',title:'Chill Night',places:[venues.creative,venues.cafe,venues.korean],price:80,match:86,reason:'A slower social plan with room to talk, make and discover.'}
];
let state={screen:'home',vibe:'surprise',member:0,votes:{Adeeb:'like',Ahmed:'pass',Kaveri:'like',Saif:'maybe'},completed:0};
let compromiseData=null;
const app=document.querySelector('#app');
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function layout(content){app.innerHTML=`<main class="shell"><nav class="topbar"><div class="brand"><span class="brand-mark">✦</span> sidequest</div><div class="top-actions"><span class="pill">WEEKEND WARRIORS</span><button class="reset" onclick="resetDemo()">Reset demo</button></div></nav>${content}</main>`}
function home(){layout(`<section class="screen"><div class="hero"><div class="hero-copy"><div class="eyebrow">Your city. Your party. Your next story.</div><h1>Make plans worth remembering.</h1><p class="sub">SideQuest turns “what should we do?” into a shared adventure — tuned to everyone's tastes, budget and energy.</p><br><button class="primary" onclick="go('plan')">✨ Plan a SideQuest <span>→</span></button></div><div class="hero-art"><div class="orb"></div></div></div><div class="section-head"><div><div class="eyebrow">THE PARTY</div><h2>Weekend Warriors</h2></div><span class="pill">GROUP LEVEL 3</span></div><div class="members">${members.map(m=>`<article class="member"><div class="avatar ${m.avatar}">${m.initials}</div><h3>${m.name}</h3><small>WEEKEND WARRIOR</small><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="budget">◈ AED ${m.budget} max</div></article>`).join('')}</div><div class="stats"><div class="stat"><strong>🔥 3</strong><span>Adventure streak</span></div><div class="stat"><strong>👾 3</strong><span>Vibies discovered</span></div><div class="stat"><strong>+680</strong><span>Group XP</span></div></div></section>`)}
function plan(){layout(`<section class="screen"><button class="back" onclick="go('home')">← Back to group</button><div class="eyebrow">QUEST BUILDER · 01</div><h2>What are we getting into?</h2><p class="sub">SideQuest Agent will cross-check everyone's preferences and find a plan the whole party can get behind.</p><div class="form-layout"><div class="panel"><div class="field"><label>WHEN?</label><div class="choice-row"><button class="choice active">Tonight</button><button class="choice">Tomorrow</button><button class="choice">This weekend</button></div></div><div class="field"><label>BUDGET PER PERSON</label><div class="choice-row"><button class="choice">AED 70</button><button class="choice active">AED 100</button><button class="choice">AED 150</button></div></div><div class="field"><label>WHAT'S THE VIBE?</label><div class="choice-row">${[['food','🍽 Food'],['activity','🎯 Activity'],['chill','😌 Chill'],['surprise','🎲 Surprise Me']].map(([id,t])=>`<button class="choice ${state.vibe===id?'active':''}" onclick="setVibe('${id}')">${t}</button>`).join('')}</div></div><div class="field"><label>OPTIONAL REQUEST</label><textarea class="request" rows="3">Something fun where we can eat and do an activity.</textarea></div><button class="primary purple" onclick="findPlans()">✨ Find our SideQuest <span>→</span></button></div><div class="panel" style="background:linear-gradient(145deg,#f0edff,#fff)"><div class="eyebrow">HOW IT WORKS</div><h2 style="font-size:24px">One agent. Four perspectives.</h2><p class="sub">The SideQuest Agent sees the full party — not just the loudest planner.</p><div class="route" style="margin-top:30px"><b>Preferences</b><br>+ <b>Budgets</b><br>+ <b>Tonight's vibe</b><br>↓<br><strong style="color:var(--purple);font-size:20px">One plan for everyone.</strong></div><div class="tags"><span class="tag">4 profiles</span><span class="tag">8 demo venues</span><span class="tag">AI + deterministic scoring</span></div></div></div></section>`)}
function finding(){layout(`<section class="screen" style="max-width:650px;margin:90px auto;text-align:center"><div class="creature" style="width:110px;height:110px"></div><div class="eyebrow">SIDEQUEST AGENT</div><h2>Finding something everyone might actually agree on...</h2><p class="sub" style="margin:auto">Checking 4 profiles, 8 demo experiences and a very real AED 100 limit.</p></section>`);setTimeout(()=>go('plans'),900)}
function planCard(p){return `<article class="plan ${p.id==='competitive'?'featured':''}"><div class="plan-icon">${p.icon}</div><div class="eyebrow">${p.id==='competitive'?'BEST GROUP MATCH':'OPTION '+(p.id==='arcade'?'02':'03')}</div><h3>${p.title}</h3><div class="route">${p.places.map((v,i)=>`${i?' <span>↓</span> ':''}<b>${v.icon} ${v.name}</b>`).join('')}</div><div class="price-row"><div class="price">AED ${p.price}<small>per person · demo estimate</small></div><div class="match">${p.match}% MATCH</div></div><p class="reason">${p.reason}</p></article>`}
function plansView(){layout(`<section class="screen"><button class="back" onclick="go('plan')">← Refine the quest</button><div class="eyebrow">SIDEQUEST AGENT · 3 OPTIONS FOR THE PARTY</div><h2>Pick your adventure.</h2><p class="sub">Complete experiences, not disconnected recommendations. Match scores are calculated from your party's preferences, budgets and vibe.</p><div class="plan-grid" style="margin-top:24px">${plans.map(planCard).join('')}</div><div style="margin-top:28px;display:flex;justify-content:flex-end"><button class="primary" onclick="go('vote')">Take it to the group →</button></div></section>`)}
function vote(){const m=members[state.member];layout(`<section class="screen"><button class="back" onclick="go('plans')">← Plans</button><div class="eyebrow">PARTY VOTE · 04</div><h2>Does the party feel it?</h2><p class="sub">Everyone gets a say. The best plan isn't the loudest person's plan.</p><div class="vote-layout" style="margin-top:22px"><div class="panel"><div class="eyebrow">VOTING AS</div><div class="vote-tabs">${members.map((x,i)=>`<button class="vote-tab ${i===state.member?'active':''}" onclick="state.member=${i};vote()">${x.name}</button>`).join('')}</div>${plans.map(p=>`<div class="vote-plan"><div class="vote-plan-top"><h3>${p.icon} ${p.title}</h3><span class="match">${p.match}%</span></div><div class="vote-buttons">${[['like','❤️ Like'],['maybe','😐 Maybe'],['pass','❌ Pass']].map(([v,t])=>`<button class="${state.votes[m.name]===v?'selected':''}" onclick="cast('${m.name}','${v}')">${t}</button>`).join('')}</div></div>`).join('')}</div><div><div class="panel results"><div class="eyebrow">CURRENT PULSE</div><h3 style="margin-top:9px">Competitive Night</h3>${members.map(x=>`<div class="result-line"><span>${x.name}</span><span>${state.votes[x.name]==='like'?'❤️':state.votes[x.name]==='maybe'?'😐':'❌'}</span></div>`).join('')}</div><div class="alert" style="margin-top:14px"><h3>🤔 No consensus</h3><p style="font-size:12px;color:#815368;line-height:1.5;margin-bottom:15px">Looks like the group wants different things. That is exactly what SideQuest is good at.</p><button class="primary purple" onclick="go('compromise')">✨ Find our compromise</button></div></div></div></section>`)}
function compromise(){const c=compromiseData||{};layout(`<section class="screen"><button class="back" onclick="go('vote')">← Back to votes</button><div class="eyebrow">SIDEQUEST AGENT · CONSENSUS MODE</div><h2>Good groups don't need perfect taste.</h2><p class="sub">They need a plan that makes everyone say, “yeah, I'd do that.”</p><div class="agent-card" style="max-width:760px;margin-top:24px"><div class="eyebrow">✨ WE FOUND A COMPROMISE</div><h2>${c.title||'Everybody gets a win.'}</h2><div class="compromise"><div class="compromise-route">${compromiseRoute()}</div><div class="price-row" style="margin-top:12px"><div class="price">AED ${c.pricePerPerson||68}<small>per person · live agent or fallback</small></div><div class="match">${c.match||96}% GROUP MATCH</div></div></div><div class="checks">${(c.reasons||["Competitive activity for Adeeb","Gaming experience for Saif","Asian food + vegetarian options for Kaveri","Within Ahmed's AED 70 budget"]).map(x=>`<div><span>✓</span> ${x}</div>`).join('')}</div><div class="agent-footer"><div class="big-score">${c.match||96}%<small>GROUP MATCH</small></div><button class="primary" onclick="go('quest')">Accept SideQuest →</button></div></div><p style="color:var(--muted);font-size:11px;margin-top:13px">${c.summary||'SideQuest Agent used the party profiles, votes and available venues to resolve the disagreement.'}</p></section>`)}
function quest(){const stops=[['🎮','Pixel Arcade','Beat one friend at an arcade game.'],['🍜','Seoul Table','Someone must order something they’ve never tried before.'],['🍦','Cloud 9 Mochi','Group votes for MVP of the night.']];layout(`<section class="screen"><div class="eyebrow">QUEST ACCEPTED · TONIGHT</div><h2>Tonight's SideQuest</h2><p class="sub">One night. Three stops. A story you'll keep bringing up.</p><div class="steps" style="margin-top:24px">${stops.map((s,i)=>`<article class="step-card"><div class="step-num">STOP 0${i+1}</div><div class="step-info"><h3>${s[0]} ${s[1]}</h3><p>Challenge: ${s[2]}</p></div><button class="complete ${state.completed>i?'done':''}" onclick="completeStop(${i})">${state.completed>i?'✓ Completed':'Complete'}</button></article>`).join('')}</div></section>`)}
function reveal(){layout(`<section class="screen"><div class="eyebrow">QUEST COMPLETE · +250 GROUP XP</div><h2>The party has a new story.</h2><div class="reveal"><div class="eyebrow">✨ NEW VIBIE DISCOVERED!</div><div class="creature"></div><h2>GLITCH</h2><div class="rarity">UNCOMMON · COMPETITIVE</div><p style="color:#d8d3f3;font-size:13px">A tiny spark of friendly rivalry. Glitch appears wherever a little competition turns into a great night.</p><div class="xp">+250 GROUP XP</div><small style="color:#c9c6de">Discovered by Weekend Warriors</small></div><button class="primary purple" onclick="go('collection')">View collection →</button></section>`)}
function collection(){layout(`<section class="screen"><div class="eyebrow">WEEKEND WARRIORS · LEVEL 4</div><h2>Your party's collection.</h2><div class="price-row" style="max-width:460px;margin:20px 0 24px"><div><strong>VIBIES</strong><div class="progress"><i></i></div></div><div style="font-weight:800">4 / 50</div></div><div class="collection-grid">${[['☕','Brewbie','Chill'],['👾','Glitch','Competitive'],['🌊','Drift','Explorer'],['✨','Luma','Foodie'],['?','Locked','???'],['?','Locked','???'],['?','Locked','???'],['?','Locked','???']].map((x,i)=>`<article class="collection-card ${i>3?'locked':''}"><div class="vibie-icon">${x[0]}</div><h3>${x[1]}</h3><small>${x[2]}</small></article>`).join('')}</div><div style="text-align:center;margin-top:35px"><p class="sub" style="margin:auto">Your friends are your party. Your city is your map. AI is your game master.</p><br><button class="primary" onclick="resetDemo()">Plan another SideQuest ↻</button></div></section>`)}
function go(screen){state.screen=screen;({home,plan,finding,plans:plansView,vote,compromise,quest,reveal,collection}[screen])()}function setVibe(v){state.vibe=v;plan()}function findPlans(){finding()}function cast(name,v){state.votes[name]=v;vote()}function completeStop(i){if(i===state.completed){state.completed++;state.completed===3?setTimeout(()=>go('reveal'),400):quest()}else quest()}function resetDemo(){state={screen:'home',vibe:'surprise',member:0,votes:{Adeeb:'like',Ahmed:'pass',Kaveri:'like',Saif:'maybe'},completed:0};compromiseData=null;home()}
function compromiseRoute(){const c=compromiseData||{stops:[{icon:'🎮',name:'Pixel Arcade'},{icon:'🍜',name:'Seoul Table'},{icon:'🍦',name:'Cloud 9 Mochi'}]};return (c.stops||[]).map((s,i)=>`${i?' <span>↓</span> ':''}${s.icon||'✦'} ${s.name}`).join('')}
async function findCompromise(){layout(`<section class="screen" style="max-width:650px;margin:90px auto;text-align:center"><div class="creature" style="width:110px;height:110px"></div><div class="eyebrow">SIDEQUEST AGENT · LIVE</div><h2>Reading the room...</h2><p class="sub" style="margin:auto">Comparing profiles, votes, budgets and live context. The fallback is ready if a provider is unavailable.</p></section>`);const payload={location:'Dubai',request:'Something fun where we can eat and do an activity.',group:members.map(m=>({name:m.name,preferences:m.tags,budget:m.budget})),votes:state.votes,plans:plans.map(p=>({id:p.id,title:p.title,price:p.price,match:p.match,places:p.places.map(v=>v.id)})),venues:Object.values(venues).map(v=>({id:v.id,name:v.name,icon:v.icon,estimatedPrice:v.price,tags:v.tags}))};try{const response=await fetch('/api/agent/compromise',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(data.ok&&data.compromise)compromiseData=data.compromise}catch(error){compromiseData=null}originalGo('compromise')}
home();
const originalGo=go;go=function(screen){if(screen==='compromise')return findCompromise();return originalGo(screen)};
